In [5]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from random import randrange
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima_model import ARIMA
from statsmodels.graphics import tsaplots

import statsmodels.api as sm
import numpy as np

In [27]:
df = pd.read_excel(r'C:\Users\treshanw\OneDrive - Star Garments\Datathon\timeseries.xlsx')

In [28]:
df

,date,median_income,population,real_estate_gdp,building_permits,total_gdp,contribution_to_wealth,customer_count,unemp,year
0,2010-01-01,52504,1829.591,15629.0,430.219652,91561.525,17.069397,13965,4.700000,2010
1,2011-01-01,55616,1840.914,16363.5,419.302428,99921.100,16.376421,12506,4.400000,2011
2,2012-01-01,52196,1853.691,17956.6,556.637107,102725.950,17.480101,18103,3.883333,2012
3,2013-01-01,57623,1865.813,18282.9,666.685258,107260.725,17.045288,15907,3.675000,2013
4,2014-01-01,56870,1879.955,20602.0,637.692058,111945.925,18.403528,10466,3.250000,2014
5,2015-01-01,60474,1892.059,22977.4,615.748070,116514.600,19.720619,15256,2.983333,2015
6,2016-01-01,59374,1906.483,23483.0,693.165681,118145.900,19.876272,18184,3.066667,2016
7,2017-01-01,59583,1916.998,26674.0,757.560607,121946.275,21.873567,14991,2.933333,2017
8,2018-01-01,67575,1925.512,27117.7,684.095353,126922.700,21.365524,13385,2.858333,2018
9,2019-01-01,73071,1932.571,28791.5,665.023746,131352.400,21.919280,15121,2.975000,2019
10,2020-01-01,72024,1937.552,30561.3,773.105890,133439.025,22.902820,10833,4.250000,2020

In [58]:
df.dtypes
df.drop(['Year'], axis=1)

,observation_date,median income,population(thousands),gdp:real estate(mn),building permits (no. of units),Total GPD,Contribution of real estate towards gdp,Customer count,Unemployment
0,2010-01-01,52504.000000,1829.591000,15629.000000,430.219652,91561.525000,17.069397,13965.000000,4.700000
1,2011-01-01,55616.000000,1840.914000,16363.500000,419.302428,99921.100000,16.376421,12506.000000,4.400000
2,2012-01-01,52196.000000,1853.691000,17956.600000,556.637107,102725.950000,17.480101,18103.000000,3.883333
3,2013-01-01,57623.000000,1865.813000,18282.900000,666.685258,107260.725000,17.045288,15907.000000,3.675000
4,2014-01-01,56870.000000,1879.955000,20602.000000,637.692058,111945.925000,18.403528,10466.000000,3.250000
5,2015-01-01,60474.000000,1892.059000,22977.400000,615.748070,116514.600000,19.720619,15256.000000,2.983333
6,2016-01-01,59374.000000,1906.483000,23483.000000,693.165681,118145.900000,19.876272,18184.000000,3.066667
7,2017-01-01,59583.000000,1916.998000,26674.000000,757.560607,121946.275000,21.873567,14991.000000,2.933333
8,2018-01-01,67575.000000,1925.512000,27117.700000,684.095353,126922.700000,21.365524,13385.000000,2.858333
9,2019-01-01,73071.000000,1932.571000,28791.500000,665.023746,131352.400000,21.919280,15121.000000,2.975000
10,2020-01-01,72024.000000,1937.552000,30561.300000,773.105890,133439.025000,22.902820,10833.000000,4.250000
11,2021-01-01,72024.000000,1956.261239,32011.969775,798.268956,137921.927036,23.210211,14141.082763,4.134621
12,2022-01-01,73170.734026,1967.638049,33568.276878,828.561791,141954.344581,23.647235,10771.949200,4.019242
13,2023-01-01,75165.501480,1979.014860,35124.583982,858.854627,145986.762127,24.060116,13012.915937,3.903864
14,2024-01-01,77160.268934,1990.391671,36680.891085,889.147462,150019.179672,24.450801,12788.575692,3.788485
15,2025-01-01,79155.036389,2001.768481,38237.198188,919.440298,154051.597218,24.821033,12975.398728,3.673106
16,2026-01-01,81149.803843,2013.145292,39793.505292,949.733133,158084.014764,25.172378,9606.265164,3.557727

In [61]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [23]:
df.columns

x = ['median income', 'population(thousands)',
       'gdp:real estate(mn)', 'building permits (no. of units) ', 'Total GPD',
       'Contribution of real estate towards gdp','Unemployment', 'Year']

In [67]:
x = df[x]
y = df['Customer count']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

lr=LinearRegression()
lr.fit(x_train, y_train)
y_pred=lr.predict(x_train)

print("Explained Variance:-",metrics.explained_variance_score(y_train, y_pred))
print("Max Error:-", metrics.max_error(y_train, y_pred))
print("Mean Absolute Error:-", metrics.mean_absolute_error(y_train, y_pred))
print("MSE:-", metrics.mean_squared_error(y_train, y_pred))
print("R-square Value:-", metrics.r2_score(y_train, y_pred))

Explained Variance:- 0.9811656413059748
Max Error:- 892.036950423595
Mean Absolute Error:- 169.043146288748
MSE:- 109773.86810542266
R-square Value:- 0.9811656413059748

In [69]:
import numpy as np
import pandas as pd

# We will use matplotlib to plot figures
import matplotlib.pyplot as plt

# For regression analysis we will use the statsmodels package
import statsmodels.formula.api as sm

# For visual inspection of the regression models
from statsmodels.graphics.regressionplots import plot_regress_exog, plot_fit, plot_leverage_resid2, influence_plot

In [4]:
m.summary()

NameError: name 'm' is not defined

In [8]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

import numpy as np

import pandas

In [33]:
df.columns

Index(['date', 'median_income', 'population', 'real_estate_gdp',
       'building_permits', 'total_gdp', 'contribution_to_wealth',
       'customer_count', 'unemp', 'year'],
      dtype='object')

In [24]:
x = ['median income', 'population(thousands)',
       'gdp:real estate(mn)', 'building permits (no. of units) ', 'Total GPD',
       'Contribution of real estate towards gdp', 'Unemployment', 'Year']
y = 'Customer count'

In [47]:
mod = smf.ols(formula='customer_count ~ median_income+population+real_estate_gdp+building_permits+total_gdp+contribution_to_wealth+unemp+year', data=df)

In [48]:
res = mod.fit()

In [49]:
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         customer_count   R-squared:                       0.396
Model:                            OLS   Adj. R-squared:                 -2.021
Method:                 Least Squares   F-statistic:                    0.1637
Date:                Wed, 13 Oct 2021   Prob (F-statistic):              0.975
Time:                        16:18:32   Log-Likelihood:                -98.585
No. Observations:                  11   AIC:                             215.2
Df Residuals:                       2   BIC:                             218.8
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept              -2.522e+07   4.74e+07     -0.532      0.648   -2.29e+08    1.79e+08
median_income             -0.5679      1.382     -0.411      0.721      -6.515       5.379
population              -442.6781   1374.626     -0.322      0.778   -6357.216    5471.860
real_estate_gdp            0.8753     27.612      0.032      0.978    -117.928     119.678
building_permits         -15.1045     49.571     -0.305      0.789    -228.392     198.182
total_gdp                 -1.6219      4.929     -0.329      0.773     -22.829      19.585
contribution_to_wealth -3161.4926   3.32e+04     -0.095      0.933   -1.46e+05     1.4e+05
unemp                  -6235.4878   1.06e+04     -0.586      0.617    -5.2e+04    3.95e+04
year                    1.308e+04   2.48e+04      0.528      0.650   -9.35e+04     1.2e+05
==============================================================================
Omnibus:                        8.831   Durbin-Watson:                   2.522
Prob(Omnibus):                  0.012   Jarque-Bera (JB):                4.071
Skew:                          -1.354   Prob(JB):                        0.131
Kurtosis:                       4.246   Cond. No.                     4.71e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.71e+09. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\treshanw\Anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [51]:
mod = smf.ols(formula='customer_count ~ median_income+population+real_estate_gdp+building_permits+total_gdp+contribution_to_wealth+unemp', data=df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         customer_count   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                 -0.076
Method:                 Least Squares   F-statistic:                    0.2898
Date:                Wed, 13 Oct 2021   Prob (F-statistic):              0.603
Time:                        16:20:11   Log-Likelihood:                -101.18
No. Observations:                  11   AIC:                             206.4
Df Residuals:                       9   BIC:                             207.2
Df Model:                           1
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept        1.638e+04   3710.738      4.414      0.002    7985.610    2.48e+04
real_estate_gdp    -0.0864      0.160     -0.538      0.603      -0.449       0.277
==============================================================================
Omnibus:                        0.297   Durbin-Watson:                   2.105
Prob(Omnibus):                  0.862   Jarque-Bera (JB):                0.432
Skew:                          -0.104   Prob(JB):                        0.806
Kurtosis:                       2.052   Cond. No.                     1.08e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.08e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\treshanw\Anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [53]:
df2 = pd.read_excel(r'C:\Users\treshanw\OneDrive - Star Garments\Datathon\wells.xlsx')

In [54]:
mod = smf.ols(formula='customer_count ~ median_income+population+real_estate_gdp+building_permits+total_gdp+contribution_to_wealth+unemp+year', data=df2)
res = mod.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         customer_count   R-squared:                       0.792
Model:                            OLS   Adj. R-squared:                 -0.039
Method:                 Least Squares   F-statistic:                    0.9533
Date:                Wed, 13 Oct 2021   Prob (F-statistic):              0.606
Time:                        16:26:01   Log-Likelihood:                -77.320
No. Observations:                  11   AIC:                             172.6
Df Residuals:                       2   BIC:                             176.2
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept               7.807e+05   6.86e+06      0.114      0.920   -2.87e+07    3.03e+07
median_income             -0.0628      0.200     -0.314      0.783      -0.923       0.798
population                98.1595    198.881      0.494      0.670    -757.554     953.873
real_estate_gdp            5.3507      3.995      1.339      0.312     -11.838      22.539
building_permits           1.1010      7.172      0.154      0.892     -29.757      31.959
total_gdp                 -1.1676      0.713     -1.637      0.243      -4.236       1.901
contribution_to_wealth -6742.4888   4807.501     -1.402      0.296   -2.74e+04    1.39e+04
unemp                  -1453.9919   1538.677     -0.945      0.444   -8074.383    5166.399
year                    -402.5882   3583.854     -0.112      0.921   -1.58e+04     1.5e+04
==============================================================================
Omnibus:                       11.304   Durbin-Watson:                   2.527
Prob(Omnibus):                  0.004   Jarque-Bera (JB):                5.651
Skew:                          -1.490   Prob(JB):                       0.0593
Kurtosis:                       4.857   Cond. No.                     4.71e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.71e+09. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\treshanw\Anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "